### PR TITLE
Jbaker/refactor focus event handling

### LINKED ISSUE #175: Improve focus tracking to better handle chrome sleeping tabs
## Describe the bug

This work is triggered from this auro-datepicker ticket: https://github.com/AlaskaAirlines/auro-datepicker/issues/93

Please see that ticket for all relevant repro steps and other details.

Dropdown needs to be updated to use a more efficient way of closing the bib when focus is lost.

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #175

## Summary:

Updates package dependencies
Refactors focus tracking to remove timeout and streamline execution

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

File: src/auro-dropdown.js [hunk 1]
```diff
@@ -180,35 +184,16 @@ class AuroDropdown extends LitElement {
...
-    if (!this.noHideOnThisFocusLoss) {
-      const focusElem = document.activeElement;
-
-      focusElem.addEventListener('blur', () => {
-        this.assessFocusWithin();
+  handleFocusLoss() {
+    if (!this.noHideOnThisFocusLoss && !this.hasAttribute('noHideOnThisFocusLoss')) {
+      document.activeElement.addEventListener('focusout', () => {
+        if (!this.contains(document.activeElement)) {
+          this.hide();
```
Comment (jordanjones243) [inline src/auro-dropdown.js:195]: There is a bug in this focus tracking. When tabbing through the dropdown, the dropdown hides when trying to give focus to the contents of the dropdown.

**Review by jordanjones243 — APPROVED** [review]
